version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: vanta-website:latest
    container_name: vanta-website
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Airtable Configuration
      - AIRTABLE_PERSONAL_ACCESS_TOKEN=${AIRTABLE_PERSONAL_ACCESS_TOKEN}
      - AIRTABLE_BASE_ID=${AIRTABLE_BASE_ID}
      # Analytics Configuration
      - NEXT_PUBLIC_GTM_ID=${NEXT_PUBLIC_GTM_ID}
      - NEXT_PUBLIC_GA_ID=${NEXT_PUBLIC_GA_ID}
      # Zapier Webhooks
      - ZAPIER_WEBHOOK_URL=${ZAPIER_WEBHOOK_URL}
      - ZAPIER_DEMO_WEBHOOK=${ZAPIER_DEMO_WEBHOOK}
      # N8N Configuration
      - N8N_API_KEY=${N8N_API_KEY}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - N8N_WEBHOOK_TEST=${N8N_WEBHOOK_TEST}
      - N8N_WEBHOOK_PROD=${N8N_WEBHOOK_PROD}
      # Cal.com Configuration
      - CALCOM_API_KEY=${CALCOM_API_KEY}
      - CALCOM_EVENT_TYPE_ID=${CALCOM_EVENT_TYPE_ID}
      # API Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
      - GOOGLE_PLACES_API=${GOOGLE_PLACES_API}
      - HUNTER_API_KEY=${HUNTER_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: vanta-website:dev
    container_name: vanta-website-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    command: npm run dev